### ISSUE TITLE
Publish/release the java client version 8.0.1 to maven central

### ISSUE THREAD

**Issue by zzur** [kubernetes-client/java#945]
Hi, we would love to pick up 8.0.1 that was released a couple of days ago.
Have not seen it on: https://search.maven.org/search?q=a:client-java-parent
Not sure if this is an issue or just a matter of time.
Can you please otherwise let me know when to expect it?
Many thanks.

**Comment by zzur** [comment]
Any/comment feedback on this? Would be greatly appreciated to know when to expect this issue to be  addressed in order to properly plan our release. 8.0.1 has fix to the basic watch() method in the generic (extended) API which does not work without it, and we would love to consume this version. Many thanks.

**Comment by brendandburns** [comment]
Yeah, I need to do this. Publishing a client is fiddly and error-prone. I will work on getting this done this week.

**Comment by brendandburns** [comment]
I pushed this to Sonatype just now. It usually takes ~1 day before it is mirrored out to Maven central.

**Comment by zzur** [comment]
many thanks !

**Comment by zzur** [comment]
Re-opening this as (so far) the issue is not really resolved. The new version does not appear on maven central for some reason.

**Comment by brendandburns** [comment]
Maven central takes a long time to replicate in my experience we can leave this open until replication completes.

--brendan

________________________________

**Comment by zzur** [comment]
looking at sonatype here: https://oss.sonatype.org/#view-repositories;public~browseindex 
I can see the artifacts published there as 8.0.1-SNAPSHOT.

When all said and done and this is mirrored on maven central, will I be pulling version 8.0.1, right? ... or is it going to be published as 8.0.1-SNAPSHOT?

**Comment by brendandburns** [comment]
Ugh maybe I messed up the version naming. I will try to repush an 8.0.2 without the Snapshot.

--brendan

________________________________

**Comment by rjeberhard** [comment]
@brendandburns, is this something we can help with? We use this project really heavily and would be willing to contribute more as there are specific tasks.
